server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://git.sungbae.net/shinyoung/wms-config.git
          default-label: main
          username: swucs
          password: n9658261