server:
  port: 9992

spring:
  application:
    name: item-service

  config:
    import: "optional:configserver:http://localhost:8888/"    #config server? url
  cloud:
    config:
      name: sycoldstorage   #config application?
      profile: dev          #config profile?

  #JPA ??
  jpa:
    properties:
      hibernate:
        #Dialect ??
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #??????? ???? ?? SQL?? ??? ??? ??
        show_sql: true
        #??? ???? JPA ?? ??? ????? ????.
        format_sql: true
        #???? ????? SQL? ??? ???? ??? ??? ??.
        use_sql_comments: true
        #???? ???? ?? ???? ???? ?????.
        ddl-auto: validate    #validate : ?? ????
        generate-ddl: false  #false : ?? ????


  datasource:
    driver-class-name: ${datasource.driver-class-name}
    url: ${datasource.url}
    username: ${datasource.username}
    password: ${datasource.password}

eureka:
  instance:
    instance-id: item-service   #??? ??? instance id
    prefer-ip-address: true
  client:
    register-with-eureka: true      #??? ????? ???
    fetch-registry: true            #??? ????? ???
    service-url:
      defaultZone: http://localhost:8761/eureka   #eureka server? url

#p6spy? ??? ?? ???? ??
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true

management:
  endpoints:
    web:
      exposure:
        include: ["env", "refresh", "info"]


encrypt:
  key: xxxx
